version: "1.0"

tags:
  component:
    description: "UI component with ownership and lifecycle metadata"
    attrs:
      id:
        type: string
        required: true
        description: "Component identifier"

  react-hook:
    description: "React hook with non-obvious behavior or cache interactions"
    attrs:
      boundary:
        type: string
        description: "Required ancestor boundary (e.g., Suspense, ErrorBoundary)"
      preload:
        type: expression
        description: "Expression to prefetch data and avoid waterfalls"
      invalidate:
        type: expression
        description: "Expression to invalidate cached data"
      invalidate-key:
        type: expression
        description: "Cache key reference for invalidation"
      error-handling:
        type: enum
        values: [throws, catches, propagates, silent]
        description: "How errors are handled (not always obvious from source)"

  controller:
    description: "API endpoint — connects frontend clients to backend handlers"
    attrs:
      method:
        type: enum
        values: [GET, POST, PUT, DELETE, PATCH, HEAD, OPTIONS]
        required: true
        description: "HTTP method"
      path:
        type: string
        required: true
        description: "URL path pattern"
      auth:
        type: enum
        values: [required, optional, none]
        default: required
        description: "Authentication requirement"
      deprecated:
        type: boolean
        description: "Whether this endpoint is deprecated"
      deprecation-target:
        type: string
        description: "Version or date when this endpoint will be removed"

  perf-critical:
    description: "Performance-sensitive code with target or tracing requirements"
    attrs:
      target:
        type: string
        description: "Performance target (e.g., '200ms', '50ms for 10k items')"
      traced:
        type: boolean
        description: "Whether distributed tracing is enabled"

  middleware:
    description: "Middleware applied to a handler — documents authorization and processing"
    attrs:
      name:
        type: string
        required: true
        description: "Middleware identifier"
      scope:
        type: string
        description: "Authorization scope expression"

  validation:
    description: "Input validation contract"
    attrs:
      schema:
        type: string
        description: "Validation schema reference"
      source:
        type: enum
        values: [body, query, params, headers]
        description: "Where validated data comes from"

  api-client:
    description: "Frontend code that calls a backend endpoint — cross-boundary flow"
    attrs:
      endpoint:
        type: string
        required: true
        description: "Backend path this client calls"
      method:
        type: enum
        values: [GET, POST, PUT, DELETE, PATCH]
        required: true
        description: "HTTP method used"

  event:
    description: "Event published or subscribed to — documents async data flow"
    attrs:
      name:
        type: string
        required: true
        description: "Event identifier"
      direction:
        type: enum
        values: [publish, subscribe]
        required: true
        description: "Whether this code publishes or subscribes"

audiences:
  product: "Product engineers building features"
  infra: "Infrastructure team maintaining internals"
  security: "Security team reviewing access control"

visibilities:
  public: "Stable API, safe to depend on"
  internal: "Implementation detail, may change"
  deprecated: "Scheduled for removal"
